/** @type {import('prettier').Config} */
export default {
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  useTabs: false,
  trailingComma: "es5",
  printWidth: 80,
  arrowParens: "always",
  endOfLine: "crlf",
  bracketSpacing: true,
  singleAttributePerLine: false,
  quoteProps: "as-needed",
  bracketSameLine: true,
  jsxSingleQuote: false,
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
  importOrder: [],
  importOrderCaseSensitive: true,
  importOrderTypeScriptVersion: "5.0.0",
  overrides: [
    {
      files: "apps/client/**/*.{ts,tsx,js,jsx,mjs,cjs}",
      options: {
        plugins: [
          "@ianvs/prettier-plugin-sort-imports",
          "prettier-plugin-tailwindcss",
        ],
        importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
        importOrder: [
          "^react$",
          "^next(.*)$",
          "<THIRD_PARTY_MODULES>",
          "",
          "^@repo/(.*)$",
          "",
          "^@/app/(.*)$",
          "^@/pages/(.*)$",
          "^@/widgets/(.*)$",
          "^@/features/(.*)$",
          "^@/entities/(.*)$",
          "^@/shared/(.*)$",
          "^@/(.*)$",
          "",
          "^[./]",
          "",
          "<TYPES>",
        ],
      },
    },
    {
      files: "apps/server/**/*.ts",
      options: {
        plugins: ["@ianvs/prettier-plugin-sort-imports"],
        importOrderParserPlugins: ["typescript", "decorators-legacy"],
        importOrder: [
          "^@nestjs/(.*)$",
          "<THIRD_PARTY_MODULES>",
          "",
          "^@repo/(.*)$",
          "",
          "^@/domain/(.*)$",
          "^@/application/(.*)$",
          "^@/infrastructure/(.*)$",
          "^@/presentation/(.*)$",
          "^@/(.*)$",
          "",
          "^[./]",
          "",
          "<TYPES>",
        ],
      },
    },
    {
      files: "packages/**/*.{ts,tsx}",
      options: {
        plugins: ["@ianvs/prettier-plugin-sort-imports"],
        importOrderParserPlugins: ["typescript"],
        importOrder: [
          "<THIRD_PARTY_MODULES>",
          "",
          "^@repo/(.*)$",
          "",
          "^[./]",
          "",
          "<TYPES>",
        ],
      },
    },
  ],
};
